### ISSUE TITLE
timecmd.bat does not work if locale use comma instead of period in floats

### ISSUE THREAD

**Issue by SuperUserNameMan** [dns/benchmark-language#1]
Hi,

If system locale uses ``,`` instead of ``.`` in floats, ``%time%`` will be rounded to integer into ``timecmd.bat``.

To make this script compatible with such locale, one has to modify it these way :
``set start=%time:,=.%``
and
``set end=%time:,=.%``

**Comment by DNS** [comment]
Fixed in https://github.com/dns/benchmark-language/commit/9453b4659671518501b8d0ca98ee6e1297bf37ab
