### ISSUE TITLE
Jitted Python!

### ISSUE THREAD

**Issue by ridulfo** [dns/benchmark-language#4]
Great repo! 👏 

I found it when I was looking for LuaJIT vs python benchmarks. However, it doesn't do Python justice! 

Could you please add a benchmark for [Pypy](https://www.pypy.org/) and for [Numba](https://numba.pydata.org/)?
I would have run it on my machine, but I do not have all the environments (e.g. C#).

This numba code yielded this benchmark:
```Python
from numba import jit
from time import time

@jit
def f(n=99999999):
        x = 1
        for i in range(0, n) :
                x = (i+i+2*i+1-0.379)/(x)
        return x

print(f(2)) # Warm up the jit
t0 = time()
print(f())
t1 = time()
print(t1-t0)
```
Output:
```
7.441223832528181
7051.571197642306
0.3768138885498047
```
0.38 seconds would put it among the fastest languages! But I understand that there might be some overhead measuring the time from batch.

**Comment by DNS** [comment]
I already plan to add pypy & ms openjdk, but this is the first time I heard about numba. 

From numba website, I get the impression that it's similar to [perl B::C module](https://metacpan.org/pod/B::C).

Also I still use the old AMD Phenom II 1090T X6, I don't think it can run faster than 0.56s (at least on my machine).

**Comment by ridulfo** [comment]
> From numba website, I get the impression that it's similar to [perl B::C module](https://metacpan.org/pod/B::C).

Depending on whether the perl C gets compiled using LLVM it might be very similar!

> Also I still use the old AMD Phenom II 1090T X6, I don't think it can run faster than 0.56s (at least on my machine).

It would be cool to have a standardised environment to run all the benchmarks. Perhaps something like GitHub actions' VMs.

**Comment by DNS** [comment]
I'm not familiar with Github actions VM. And some of the benchmarks exclusively need Windows with commercial software (.NET CLR & Embarcadero).

I plan to add pypi, numba, PHP, .NET Core, ms openjdk, free pascal,  & delphi probably in the next few weeks.

**Comment by DNS** [comment]
https://github.com/DNS/benchmark-language/commit/ee6c42ce42df2154e71d3035d90624f2ec19aa57

I've upgraded to AMD FX-8300 last year, but apparently (single core) FX-8300 run slower -30% to -36% than the older AMD Phenom II 1090T X6. 😂

```
Numba (Python 3.11.3) on AMD FX-8300: 2.17s

C (MSVC 18, VS 2013) on AMD Phenom II 1090T X6: 0.56s
C (MSVC 18, VS 2013) on AMD FX-8300: 0.80s

PowerShell 5.1 on AMD Phenom II 1090T X6: about ~36s
PowerShell 5.1 on AMD FX-8300: 56.65s
```
