### ISSUE TITLE
Update LuaJIT

### ISSUE THREAD

**Issue by joaopauloalbq** [dns/benchmark-language#7]
Hi Daniel o/

Version _2.0.5_ of LuaJIT is really old and recommended only for compatibility reasons. Please use version _2.1.ROLLING_ which is recommended for production use.

source: https://luajit.org/status.html

**Comment by DNS** [comment]
Updated to LuaJIT 2.1.1694442928 through `winget install DEVCOM.LuaJIT`

https://github.com/DNS/benchmark-language/commit/7de3986107b43c3c51da532d1b1d4345ef380e3d

The new LuaJIT 2.1 is a little bit slower **(0.81s)** than the older LuaJIT 2.0.5 **(0.79s)**

**Comment by joaopauloalbq** [comment]
Strange, on my machine _LuaJIT_ is the fastest, even faster than _C_:

```
C          580.24 millis
LuaJIT     433.60 millis
```

According to your commit you retested only LuaJIT... 
Wouldn't it be more appropriate to run all the tests again?

**Comment by DNS** [comment]
I've rerun the benchmark (running on AMD FX-8300) several times after I upgraded my CPU, and I only take the fastest time. There's no need to rerun the benchmark again.
In the past I use Phenom II X6 1090T, then upgraded to FX-8300. But the newer FX-8300 benchmark results slower than the older Phenom II X6 (which is consistent with other benchmarks). 

You certainly using newer CPU that has more additional instructions & predictive branching that probably give LuaJIT advantage.

```
C (MSVC 18, VS 2013) on AMD Phenom II 1090T X6: 0.56s
C (MSVC 18, VS 2013) on AMD FX-8300: 0.80s

PowerShell 5.1 on AMD Phenom II 1090T X6: about ~36s
PowerShell 5.1 on AMD FX-8300: 56.65s

```

**Comment by joaopauloalbq** [comment]
> You certainly using newer CPU that has more additional instructions & predictive branching that give LuaJIT advantage.

Makes sense...

I'm using Intel i5 8250U and Arch Linux

**Comment by DNS** [comment]
```
C          580.24 millis
LuaJIT     433.60 millis
```

I think you probably compiled it wrong. The C binary should be faster than 0.58s on Intel i5 8250U.  On older AMD Phenom II 1090T X6 it's 0.56s. It doesn't make sense CPU from 2010 can beat CPU released in 2017!

https://cpu.userbenchmark.com/Compare/Intel-Core-i5-8250U-vs-AMD-Phenom-II-X6-1090T/m338266vsm417

Have you tried using `gcc -O3 test.c`  or `clang -O3 test.c` as in https://github.com/DNS/benchmark-language/blob/master/build.sh ?

Also don't forget to turn off power saving mode in UEFI/BIOS & OS settings when running benchmark.

**Comment by joaopauloalbq** [comment]
> Have you tried using gcc -O3 test.c

That's it, I was using standard gcc (`gcc test.c -o test`), totally missed that.

> don't forget to turn off power saving mode

CPU frequency scaling governor changed now, from powersave to performance.



New results: 
- CPU governor on performance
- gcc with performance optimization

```
C          414.20 millis
LuaJIT     414.70 millis
```
